-- DATA EXPLORATION
select* from zepto_v2;

-- count of rows

select count(*) from zepto_v2;

-- SAMPLE DATA
SELECT * FROM ZEPTO_V2
LIMIT 10;

-- NULL VALUES
SELECT * FROM ZEPTO_V2
WHERE NAME IS NULL
OR 
MRP IS NULL
OR
CATEGORY IS NULL
OR
DISCOUNTPERCENT IS NULL
OR
AVAILABLEQUANTITY IS NULL
OR 
DISCOUNTEDSELLINGPRICE IS NULL
OR
WEIGHTINGMS IS NULL
OR 
QUANTITY IS NULL
OR
OUTOFSTOCK IS NULL;

-- DIFFERENT PRODUCT CATEGORIES
SELECT DISTINCT CATEGORY
FROM ZEPTO_V2
ORDER BY CATEGORY;

-- PRODUCT IN STOCK VS OUT OF STOCK
SELECT OUTOFSTOCK,COUNT(TRUE)
FROM ZEPTO_V2
GROUP BY OUTOFSTOCK;

SELECT* FROM ZEPTO_V2;

SELECT 
    ROW_NUMBER() OVER () AS serial_no,
    NAME,CATEGORY,MRP,DISCOUNTPERCENT,AVAILABLEQUANTITY,DISCOUNTEDSELLINGPRICE,WEIGHTINGMS,QUANTITY,OUTOFSTOCK
    
FROM ZEPTO_V2;

-- PRODUCT NAMES PRESENT MULTIPLE TIMES
SELECT NAME, COUNT(SERIAL_NO) AS "NUMBER OF SERIALS"
FROM ZEPTO_V2
GROUP BY NAME
HAVING COUNT(SERIAL_NO)=15
ORDER BY COUNT(SERIAL_NO) DESC;

-- DATA CLEANING

-- PRODUCTS WITH PRICE =0
SELECT * FROM ZEPTO_V2
WHERE MRP=0 OR DISCOUNTEDSELLINGPRICE=0;

DELETE FROM ZEPTO_V2
WHERE mrp = 0;

-- convert paise to rupees

UPDATE ZEPTO_V2
SET MRP=MRP/100.0,
DISCOUNTEDSELLINGPRICE= DISCOUNTEDSELLINGPRICE/100.0;

SELECT MRP,DISCOUNTEDSELLINGPRICE FROM ZEPTO_V2;

-- Q1- FIND THE TOP 10 BEST VALUE PRODUCTS BASED ON THE DISCOUNT PERCENATAGE?
SELECT DISTINCT name, MRP, discountPercent
FROM ZEPTO_V2
ORDER BY discountPercent DESC
LIMIT 10;

-- Q2 WHAT ARE THE PRODUCTS WITH HIGH MRP BUT OUT OF STOCK
SELECT DISTINCT NAME,MRP
FROM ZEPTO_V2
WHERE MRP > 300 AND OUTOFSTOCK= 'true'
ORDER BY MRP DESC;

-- Q3 CALCULATE THE ESTIMATED REVENUE FOR EACH CATEGORY?
SELECT CATEGORY,
SUM(DISCOUNTEDSELLINGPRICE * AVAILABLEQUANTITY) AS TOTAL_REVENUE
FROM ZEPTO_V2
GROUP BY CATEGORY
ORDER BY TOTAL_REVENUE;

-- Q4 FIND ALL THE PRODUCT WHERE MRP IS GREATER THSN 500 AND DISCOUNT IS LESS THAN 10%
SELECT DISTINCT NAME,MRP,DISCOUNTPERCENT
FROM ZEPTO_V2
WHERE MRP > 500 AND DISCOUNTPERCENT < 10
ORDER BY MRP DESC , DISCOUNTPERCENT DESC;

-- Q5 IDENTIFY THE TOP 5 CATEGORIES OFFERING THE HIGHEST AVERAGE DISCOUNT PERCENTAGE?
SELECT CATEGORY,
ROUND(AVG(DISCOUNTPERCENT),2) AS AVG_DISCOUNT
FROM ZEPTO_V2
GROUP BY CATEGORY
ORDER BY AVG_DISCOUNT DESC
LIMIT 5;

-- Q6 FIND THE PRICE PER GRAM FOR PRODUCTS ABOVE 100G AND SORT BY BEST VALUE?
SELECT distinct NAME, discountedsellingprice, weightInGms,
ROUND(DISCOUNTEDSELLINGPRICE / weightInGms,2) AS PRICE_PER_GRAMS
FROM ZEPTO_V2
WHERE weightInGms >=100 
ORDER BY PRICE_PER_GRAMS;

-- Q7 GROUP THE PRODUCTS INTO CATEGORIES LIKE LOW , MEDUM, BULK.
SELECT DISTINCT NAME, weightInGms,
CASE WHEN weightInGms < 1000 THEN 'LOW'
     WHEN weightInGms < 5000 THEN 'MEDIUM'
     ELSE 'BULK'
     END AS weight_category
FROM ZEPTO_V2;

-- Q8 WHAT IS THE TOTAL INVENTORY WEIGHT PER CATEGORY?
SELECT CATEGORY,
SUM(weightInGms* availablequantity) AS TOTAL_WEIGHT
FROM ZEPTO_V2
GROUP BY CATEGORY
ORDER BY TOTAL_WEIGHT;











   


